language: python
python:
- '2.7'
- '3.3'
before_install:
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- "./miniconda.sh -b"
- export PATH=/home/travis/miniconda/bin:$PATH
- conda update --yes conda
- sudo rm -rf /dev/shm
- sudo ln -s /run/shm /dev/shm
install:
- conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib nose
  dateutil pandas statsmodels
- conda install --yes -c dan_blanchard python-coveralls nose-cov
- pip install coveralls
- python setup.py install
script: nosetests --with-coverage --cover-package=ddbscan --logging-level=INFO
after_success:
- coveralls --config_file .coveragerc
deploy:
  provider: pypi
  user: allanino
  password:
    secure: ME8sSq4zD7qrshqVyIZv86IOqgKaXOVtosQ+76aRwxrGUCLhTrapeYji49CVKlug3b33MiIxiZeHwwZsh7HqdS1FzneCPxTqSijh48CssUWJJ3OCVRutpQONwvD7n1ZzzhsWo8gFN/vFZOSLl7+bCpdm1OXzxM2sTnVR2NM4tZY=
  on:
    all_branches: true
    tags: true
    repo: cloudwalkio/ddbscan
